### ISSUE TITLE
Provide registerVoteBatch(...)

### ISSUE THREAD

**Issue by ledfusion** [vocdoni/go-dvote#13]
- [ ] IPFS integration
- [ ] Define VoteBatch structure
- [ ] Send hash/link to web3/Ethereum

**Comment by imw** [comment]
For ipfs integration, I think we can/should use this:
https://github.com/ipfs/go-ipfs
Details of usage as a library can be found here:
https://github.com/ipfs/go-ipfs/issues/3060

**Comment by imw** [comment]
For registering batches on chain:
https://github.com/ethereum/go-ethereum
