### ISSUE TITLE
Refactor router

### ISSUE THREAD

**Issue by imw** [vocdoni/go-dvote#32]
We should make the following improvements:
* Allow methods/callbacks to be registered to a central router object
* Have methods unmarshal message JSON into type-specific structs
* Do away with format strings

**Comment by NateWilliams2** [comment]
Items 2+3 are implemented in branch refactor/routers commit "refactor router to structify response and error messages"

Will work on item 1 moving forward!

**Comment by NateWilliams2** [comment]
This issue is being worked on in pull request #34
